---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: httpd-deployment
    labels:
      app: food-master
spec:
 replicas: 3
 selector:
     matchLabels:
      app: food-master
 template:
     metadata:
        labels:
            app: food-master
     spec:
       containers:
         - name: httpd2
           image: saidevops94/repos:latest
           imagePullPolicy: "Always"
           ports:
           - containerPort: 80
